### ISSUE TITLE
curious about the meaning of copy_leaf_dummy in pruning

### ISSUE THREAD

**Issue by can-007** [facebookresearch/aroma-paper-artifacts#3]
I read about this line:
https://github.com/facebookresearch/aroma-paper-artifacts/blob/master/reference/src/main/python/similar.py#L473
It seems copy_leaf_dummy() removes the property: `"leaf": true`.
This will affect the sibling feature and the var usage feature.
What is the point?
Is it to be an example of how do do customization of Aroma?

**Comment by can-007** [comment]
This is a silly question.
Removing `{"leaf": true}` is how Aroma does pruning.

**Comment by frank-lsf** [comment]
Spot on :)

Note that there are quite a few functions in `similar.py` that is not used; those are the different things we tried for finding the best recommendation algorithm.
