### ISSUE TITLE
Parsers for other languages

### ISSUE THREAD

**Issue by Manas-Embold** [facebookresearch/aroma-paper-artifacts#4]
Hi 
I watched the presentation video of the project on youtube.
Are there any plans to make available parsers for other languages as well.
Else, can you guide me to any resource to help build parsers for other languages (js / python / cpp)

**Comment by frank-lsf** [comment]
Hi!

The Java parser is intended as a reference implementation. There is no plan to release parsers for other languages.

The easiest way to implement a new parser would be to find the ANTLR4 grammar for that language (https://github.com/facebookresearch/aroma-paper-artifacts/tree/master/reference/src/main/antlr4), then play with it a bit to see if the parse tree makes sense. In our experience it usually requires slight modifications to the grammar or post-processing of the parse trees to get the best results.

**Comment by Manas-Embold** [comment]
Thanks much !

**Comment by Zero0one1** [comment]
@Manas-Embold Hi! I'm working on writing a parser for Python. May I ask do you successfully write it?
